app:
  name: techtrends
  
namespace:
  name: prod
  
replicaCount: 5
 
image:
  repository: kashifilyasansys/techtrends 
  tag: latest
  pullPolicy: Always

containerPort: 3111
livenessProbe: /healthz
readinessProbe: /healthz

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m
    
service:
  port: 7111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP