app:
  name: techtrends
  
namespace:
  name: staging
  
replicaCount: 3
 
image:
  repository: kashifilyasansys/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 3111
livenessProbe: /healthz
readinessProbe: /healthz

resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:
    memory: 128Mi
    cpu: 500m
    
service:
  port: 5111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP